# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MCTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge',
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  # Pods for MCTest
  pod 'MobileCenter/Crashes', '~> 0.12.1'
  pod 'MobileCenter/Analytics', '~> 0.12.1'
  pod 'RNMobileCenterShared', '~> 0.9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  

  target 'MCTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'MCTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MCTest-tvOS

  target 'MCTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
